# Generated by Django 4.0.5 on 2022-06-15 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='steam_ID',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_data.player')),
            ],
        ),
    ]
